- hosts: all
  gather_facts: no
  collections:
    - arubanetworks.aoscx
  tasks:
    - name: Adding or Updating Banner
      aoscx_banner:
        banner_type: banner
        banner: "Hi!"
    - name: Create VLAN 200 with description
      aoscx_vlan:
        vlan_id: 200
        description: This is VLAN 200
    - name: Create VLAN 300 with description and name
      aoscx_vlan:
        vlan_id: 300
        name: UPLINK_VLAN
        description: This is VLAN 300
    - name: Retrieve all information from the device and save into a variable "facts_output"
      aoscx_facts:
      register: facts_output

- hosts: all
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: network_cli
  tasks:
    - name: Execute show run on the switch
      aoscx_command:
        commands: ['show run']
